config/routes.rb
Rails.application.routes.draw do
  root 'home_pages#home'
  get    '/signup', to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/login',  to: 'sessions#destroy'
  resources :users
  resources :rooms
  resources :reservations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :guests, numericality: {
      only_integer: true, 
      greater_than: 0, 
      less_than: 100
  }
  validate :start_date_check
  validate :dates_check

  private

    def dates_check
      if !start_date.nil? && !end_date.nil?
        if self.end_date <= self.start_date
          self.errors.add(:base, "チェックアウト予定日はチェックイン以降の日付を選択してください") 
        end
        if self.start_date.since(1.month) < self.end_date
          self.errors.add(:base, "1ヶ月以上の連泊はできません")
        end
        #期間に重複がないか確認
        if (self.id.nil? && self.room.reservations.where(
              'end_date >= ? and start_date <= ?',self.start_date, self.end_date).present?) ||
           (!self.id.nil? && self.room.reservations.where(
               'end_date >= ? and start_date <= ? and id != ?',self.start_date, self.end_date, self.id).present?)
          self.errors.add(:base, "指定された日付は予約済です")
        end
      end
    end
    
    def start_date_check
      if !start_date.nil?
        if self.start_date < Date.today
          self.errors.add(:base, "チェックインは本日以降の日付を選択してください") 
        end
        if Date.today.since(3.month) < self.start_date
          self.errors.add(:base, "チェックインは本日より3ヶ月以内の日付を選択してください") 
        end
      end
    end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations
  validates :user_id, presence: true
  validates :name, presence: true
  validates :location, presence: true
  validates :price, numericality: {
      only_integer: true, 
      greater_than_or_equal_to: 0, 
      less_than_or_equal_to: 1000000
  }
  validates :introduction, presence: true
  mount_uploader :image, ImageUploader
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms
  has_many :reservations
  before_save :downcase_email
  has_secure_password
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true,
                    length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :introduction, length: { maximum: 50 }
  #更新時のみパスワード省略可のため、allow_nilをセット
  validates :password, presence:true, length: { maximum: 10 }, allow_nil: true
  mount_uploader :image, ImageUploader
  
  private
  # メールアドレスをすべて小文字にする
    def downcase_email
      self.email.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include RoomsHelper
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @reservations = current_user.reservations
  end
  
  def show
    @reservation = Reservation.find_by(id: params[:id])
  end
  
  def create
    @reservation = current_user.reservations.build(reservation_params)
    @reservation.total_fee = calc_total_fee(@reservation)
    if @reservation.save
      flash[:success] = "ルームの予約が完了しました"
      redirect_to @reservation
    else
      @room = Room.find(@reservation.room_id)
      render 'rooms/show'
    end
  end
   
  def edit
    @reservation = Reservation.find_by(id: params[:id])
  end
  
  def update
    @reservation = Reservation.find_by(id: params[:id])
    @reservation.total_fee = calc_total_fee(@reservation)
    if @reservation.update(reservation_params)
      flash[:success] = "予約情報を更新しました"
      redirect_to @reservation
    else
      render 'edit'
    end
  end
  
  def destroy
    @reservation = Reservation.find(params[:id])
    #binding.pry
    @reservation.delete
    @reservations = current_user.reservations
    flash[:info] = "予約をキャンセルしました"
    redirect_to reservations_path
  end
  
    private

    def reservation_params
      params.require(:reservation).permit(:start_date, :end_date, :guests, :total_fee, :room_id)
    end
    
    #宿泊費用を計算
    def calc_total_fee(reservation)
      if reservation.start_date.present? && reservation.end_date.present?
        price = Room.find(reservation.room_id).price
        term = (reservation.end_date - reservation.start_date).to_i
        guests = reservation.guests.to_i
        price * term * guests
      end
    end
    
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def index
    #エリア,キーワード入力時
    if params[:name].present? || params[:location].present?
      @rooms = Room.where('name like ?', "%#{params[:name]}%").where('location like ?', "%#{params[:location]}%").order(updated_at: "DESC")
      @keyword = params[:name]
      @location = params[:location]
    else
      @rooms = Room.all.order(updated_at: "DESC")
    end
  end
  
  def new
    @room = Room.new
  end
  
  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      flash[:success] = "ルーム登録が完了しました"
      redirect_to @room
    else
      render 'new'
    end
  end

  def edit
    @room = Room.find(params[:id])
  end
  
  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to @room
    else
      render 'edit'
    end
  end
  
  def destroy
    room = Room.find(params[:id])
    room.delete
    flash[:info] = "ルームを削除しました"
    redirect_to current_user
  end
  
  private
    
    def room_params
      params.require(:room).permit(:name, :introduction, :location, :price, :image)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user&.authenticate(params[:session][:password])
      log_in user
      flash[:info] = "ログインに成功しました"
      redirect_to user
    else
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザー登録が完了しました"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :introduction, :password, :password_confirmation, :image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def owner?(room)
    logged_in? && current_user.rooms.include?(room)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  #ログイン中のユーザーを返す
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  #ログイン状態を返す
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/views/home_pages/home.html.erb
<section class="section-top home">
  <div class="top-block">
    <h2 class="top-title">Air 6n6 で、<br>素敵な日本を体験しませんか？</h2>
    <%= form_with url: rooms_path, method: :get, local: true do |f| %>
      <%= f.label :location, 'エリア' %>
      <%= f.text_field :location, class: 'top-search-form', placeholder: 'ex. 東京' %>
      <%= f.submit '探す', class: 'top-button' %>
      <%= link_to('新しいルームを登録する', new_room_path) if logged_in? %>
    <% end %>
  </div>
</section>

app/views/layouts/_header.html.erb
<header>
  <div class="header-inner contents-tidy">
    <div class="header-left-block contents-tidy">
      <div class="air6n6-logo">
        <%#= image_tag 'air6n6_logo.png' %>
        <%= link_to image_tag('air6n6_logo.png'), root_url %>
      </div>
      
      <%= form_with url: rooms_path, method: :get, local: true ,class: 'search-box' do |f| %>
        <%= f.text_field :location, class: 'header-form', value: @location, placeholder: 'エリア検索' %>
        <i class="fas fa-map-marker-alt header-form-icon area"></i>

        <%= f.text_field :name, class: 'header-form', value: @keyword, placeholder: 'キーワード検索' %>
        <i class="fas fa-search header-form-icon keyword"></i>
        <%= f.submit '', class: 'hide' %>
      <% end %>
      
    </div>
      <% if logged_in? %>
        <div class="header-right-block logged_in">
          <%= link_to 'マイページ', current_user, class: 'login-button signup logged_in' %>
          <%= link_to 'ログアウト', login_path, method: :delete, class: 'login-button login logged_in' %>
        </div>
      <% else %>
        <div class="header-right-block">
          <%= link_to '登録', signup_path, class: 'login-button signup' %>
          <%= link_to 'ログイン', login_path, class: 'login-button login' %>
        </div>
      <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Air6n6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if flash.any? %>
      <% flash.each do |type, message| %>
        <p class="flash <%= type %>"><%= message %></p>
      <% end %>
    <% end %>
    <main class="content-width <%= controller.controller_name %>">
      <%= yield %>
    </main>
  </body>
</html>

app/views/reservations/edit.html.erb
<section class="section-top">
  <div class="reservation-block">
    <%= render 'shared/room_info', room: @reservation.room %>
    <div class="reservation-detail">
      <h3 class="title">予約を変更する</h3>
      <%= render 'shared/reservation_form',
        reservation: @reservation, room_id: @reservation.room_id, submit_text: "変更を完了する" %>
    </div>
  </div>
  <div class="another-menu">
    <p><%= link_to 'このルームのオーナー情報を表示', @reservation.room.user %></p>
    <p><%= link_to '予約済みルーム一覧', :reservations %></p>
  </div>
</section>
<%= javascript_pack_tag 'reservation/calc_total_fee' %>

app/views/reservations/index.html.erb
  <section class="section-top">
    <h2>予約済みルーム一覧</h2>
    <% if @reservations.present? %>
      
    <table class="reservations_list">
      <tr>
        <th>ルーム写真</th>
        <th>ルーム名</th>
        <th>ロケーション</th>
        <th>合計料金</th>
        <th>チェックイン/チェックアウト</th>
        <th>予約確定日時</th>
      </tr>
      
      <% @reservations.each do |reservation| %>
        <tr>
            <td class="room-thumbnail">
              <% if reservation.room.image? %>
                <%= image_tag reservation.room.image.thumb.url %>
              <% else %>
                <%= image_tag('room_sample.jpeg') %>
              <% end %>
            </td>
            <td><%= link_to reservation.room.name, reservation %></td>
            <td><%= reservation.room.location %></td>
            <td>¥ <%= reservation.total_fee %></td>
            <td><%= reservation.start_date %> / <%= reservation.end_date %></td>
            <td><%= reservation.created_at.to_s(:datetime_jp) %></td>
         </tr>
      <% end %>  
    </table> 

  <% else %>
  <p>予約済みのルームはありません</p>
  <% end%>
  </section>

app/views/reservations/show.html.erb
<section class="section-top">
  <div class="reservation-block">
    <%= render 'shared/room_info', room: @reservation.room %>
    <div class="reservation-detail">
      <h3 class="title">予約情報</h3>
      <table class="reservation-info">
        <tr>
          <th>人数</th>
          <td><%= @reservation.guests %> 人</td>
        </tr>
        <tr>
          <th>合計金額</th>
          <td>¥ <%= @reservation.total_fee %></td>
        </tr>
        <tr>
          <th>チェックイン</th>
          <td><%= @reservation.start_date %></td>
        </tr>
        <tr>
          <th>チェックアウト</th>
          <td><%= @reservation.end_date %></td>
        </tr>
      </table>
    </div>
  </div>
  
  <ul class="another-menu">
    <li><%= link_to '予約情報を変更する', edit_reservation_path(@reservation) %></li>
    <li><%= link_to '予約をキャンセルする', @reservation, method: :delete, data: { confirm: "本当にキャンセルしますか？" }  %></li>
    <li><%= link_to 'このルームのオーナー情報を表示', @reservation.room.user %></li>
  </ul>  
</section>

app/views/rooms/_guests_list.html.erb
<% if room.reservations.present? %>
  <h3>このルームの予約情報</h3>
  <table class="guests_list">
    <tr>
      <th>ゲスト名</th>
      <th>チェックイン / チェックアウト</th>
      <th>人数</th>
      <th>合計金額</th>
      <th>予約完了日</th>
    </tr>
      
    <% room.reservations.each do |reservation| %>
      <tr>
        <td><%= link_to reservation.user.name, reservation.user %></td>
        <td><%= reservation.start_date %> / <%= reservation.end_date %></td>
        <td><%= reservation.guests %></td>
        <td>¥ <%= reservation.total_fee %></td>
        <td><%= reservation.created_at.to_s(:datetime_jp) %></td>
      </tr>
    <% end %>  
  </table> 
<% else %>
  <h3>このルームの予約情報はありません</h3>
<% end %>
  

app/views/rooms/_room_form.html.erb
<%= form_with(model: room, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <table class="reservation-info">
    <tr>
      <th><%= f.label :name, 'ルーム名' %></th>
      <td><%= f.text_field :name, placeholder:'ルーム名を入力' %></td>
    </tr>
    <tr>
      <th><%= f.label :image, 'ルーム写真' %></th>
      <td><%= f.file_field :image %></td>
    </tr>
    <tr>
      <th><%= f.label :introduction, 'ルーム紹介' %></th>
      <td><%= f.text_area :introduction, placeholder:'紹介文を入力' %></td>
    </tr>
    <tr>
      <th><%= f.label :location, 'ロケーション' %></th>
      <td><%= f.text_field :location, placeholder: 'ロケーションを入力'%></td>
    </tr>
    <tr>
      <th><%= f.label :price, '料金(1泊あたり)' %></th>
      <td><%= f.text_field :price, placeholder: '料金を入力'%></td>
    </tr>
  </table>
  <%= f.submit submit_text, class: 'submit-button' %>
<% end %>

app/views/rooms/edit.html.erb
<section class="section-top">
  <div class="reservation-block">
    
    <%= render 'shared/room_info', room: @room %>
    <div class="reservation-detail">
      <h3 class="title">ルーム情報を変更する</h3>
      <%= render 'room_form', room: @room, submit_text: "更新" %>
    </div>
    
  </div>
</section>

app/views/rooms/index.html.erb
<section class="section-top room-list">
  <h2>ルーム一覧   (検索結果：<%= @rooms.count %>件)</h2>
  <div class="room-block">
   <% @rooms.each do |room| %>
      <%= link_to room, class: 'room-box' do %>
      <!--div class="room-box"-->
        <div class="room-thunmnail">
          <% if room.image? %>
            <%= image_tag room.image.url %>
          <% else %>
            <%= image_tag('room_sample.jpeg') %>
          <% end %>
        </div>
        <div class="room-profile">
          <p class="room-name"><%= room.name %></p>
          <p class="room-location"><%= room.location %></p>
          <p class="room-price">¥ <%= room.price %></p>
        </div>
      <% end %>  
    <% end %>  
  </div>  
</section>

app/views/rooms/new.html.erb
<section class="section-top register-room">

  <div class="reservation-detail">
    <h3 class="title">新しいルームを登録する</h3>
    <%= render 'room_form', room: @room, submit_text: "登録を完了する" %>
  </div>
 
</section>

app/views/rooms/show.html.erb
<section class="section-top room-detail">
  <div class="reservation-block">
    <%= render 'shared/room_info', room: @room %>
    
    <% if owner?(@room) %>
      <div class="guests_info">
        <%= render 'guests_list',room: @room %>
      </div>
    <% else %>
      <div class="reservation-form">
        <h3 class="title">このルームを予約する</h3>
        <%= render 'shared/reservation_form',
          reservation: @reservation, room_id: @room.id, submit_text: "変更を完了する" %>
      </div>
    <% end %>
    
  </div>
  <div class="another-menu">
    <% if !owner?(@room) %>
      <p><%= link_to('このルームのオーナー情報を表示', @room.user) %></p>
      <p><%= link_to '予約済みルーム一覧', :reservations %></p>
    <% else %>
      <ul>
        <li><%= link_to 'このルーム情報を編集する', edit_room_path(@room) %></li>
        <li><%= link_to 'このルームを削除する', @room, method: :delete, data: { confirm: "本当にキャンセルしますか？" } %></li>
      </ul>
    <% end %>
  </div>
</section>

<%= javascript_pack_tag 'reservation/calc_total_fee' %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <ul class="error_message">
    <% object.errors.full_messages.each do |error_message| %>
      <li><%= error_message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_reservation_form.html.erb
<%= form_with(model: reservation, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    
  <table class="reservation-info">
    <tr>
      <th><%= f.label :start_date, 'チェックイン日付' %></th>
      <td><%= f.date_field :start_date, id: 'start_date' %></td>
    </tr>
    <tr>
      <th><%= f.label :end_date, 'チェックアウト日付' %></th>
      <td><%= f.date_field :end_date, id: 'end_date' %></td>
    </tr>
    <tr>
      <th><%= f.label :guests, '人数', class: 'guests' %></th>
      <td><%= f.number_field :guests, id: 'guests', placeholder: '予約人数を入力'%></td>
    </tr>
    <tr>
      <th>合計金額</th>
      <td id ="total_fee">¥ <%= reservation.total_fee %></td>
    </tr>
  </table>
  <%= hidden_field_tag 'reservation[room_id]', room_id %>
  
  <% if logged_in? %>
    <%= f.submit submit_text, class: 'submit-button' %>
  <% else %>
    <%= link_to 'ログイン', login_path, class: 'login-btn' %>
  <% end %>
  
<% end %>
   

app/views/shared/_room_info.html.erb
<div class="_room_info" >
  <h1 class="room-name"><%= room.name if !room.id.nil? %></h1>
  <p class="room-text"><%= room.introduction if !room.id.nil? %></p>
  <div class="room-thunmbnail">
    <% if room.image? %>
      <%= image_tag room.image.thumb.url %>
    <% else %>
      <%= image_tag 'room_sample.jpeg' %>
    <% end %>
  </div>
  <% if !room.id.nil? %>
    <div class="room-profile">
      <span class="room-location">
        <i class="fas fa-map-marker-alt header-form-icon"></i>
        <%= room.location %>
      </span>
      <span class="room-price">¥<span id = "price"><%= room.price %></span> /泊</span>
    </div>
  <% end %>
</div>

app/views/users/_owner_info.html.erb
<% if user.rooms.present? %>
  <h3>このオーナーのルーム情報</h3>
  <table class="reservations_list">
    <tr>
      <th>ルーム写真</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>ロケーション</th>
      <th>料金(1泊)</th>
      <th>ルーム登録日</th>
    </tr>
      
    <% user.rooms.each do |room| %>
      <tr>
        <td class="room-thumbnail">
          <% if room.image? %>
            <%= image_tag(room.image.thumb.url) %>
          <% else %>
            <%= image_tag('room_sample.jpeg') %>
          <% end %>
        </td>
        <td><%= link_to room.name, room %></td>
        <td><%= room.introduction %></td>
        <td><%= room.location %></td>
        <td>¥ <%= room.price %></td>
        <td><%= room.created_at.to_s(:datetime_jp) %></td>
      </tr>
    <% end %>  
  </table> 
<% else %>
  <h3>このオーナーのルーム情報はありません</h3>
<% end %>
  

app/views/users/_user_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <table class="user-form">
    <tr>
      <th><%= f.label :name, '名前' %></th>
      <td><%= f.text_field :name, placeholder: '名前を入力'%></td>
    </tr>
    <tr>
      <th><%= f.label :emain, 'Eメール' %></th>
      <td><%= f.email_field :email, placeholder: 'メールアドレスを入力'%></td>
    </tr>
    <tr>
      <th><%= f.label :introduction, '自己紹介' %></th>
      <td><%= f.text_area :introduction, placeholder: '自己紹介を入力'%></td>
    </tr>
    <tr>
      <th><%= f.label :image, 'プロフィール写真' %></th>
      <td><%= f.file_field :image %></td>
    </tr>
    <tr>
      <th><%= f.label :password, 'パスワード' %></th>
      <td><%= f.password_field :password %></td>
    </tr>
    <tr>
      <th><%= f.label :password_confirmation, 'パスワード再入力' %></th>
      <td><%= f.password_field :password_confirmation %></td>
    </tr>
  </table>
  <%= f.submit submit_text, class: 'submit-button' %>
<% end %>

app/views/users/edit.html.erb
<section class="section-top user-edit picture">
  <div class="user-form-box">
    <h2>ユーザー情報編集</h2>
    
    <section class="user_form">
      <%= render 'user_form', user: @user, submit_text: '編集を完了する' %>
    </section>

  </div>
</section>

app/views/users/new.html.erb
<section class="section-top signup picture">
  <div class="user-form-box">
    <h2>新規ユーザ登録</h2>
     
    <section class="user_form">
      <%= render 'user_form', user: @user, submit_text: '登録を完了する' %>
    </section>
    
  </div>
</section>

app/views/users/show.html.erb
<section class="section-top user-page">
  <h2 class="user-page-title">ユーザー情報</h2>
  <div class="user-profile-block">
    <div class="user-thumbnail">
      <% if @user.image? %>
        <%= image_tag @user.image.thumb.url %>
      <% else %>
        <%= image_tag 'no_image.jpeg' %>
      <% end %>
    </div>
    <div class="user-profile">
      <table>
        <tr>
          <th>名前</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th>メール</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th>自己紹介</th>
          <td><%= @user.introduction %></td>
        </tr>
      </table>
      <% if @user == current_user %>
        <ul class="user-menu">
          <li><%= link_to '新しいルームを登録する', new_room_path %></li>
          <li><%= link_to '予約済みルームを確認する', reservations_path %></li>
          <li><%= link_to 'ユーザー情報を編集する', edit_user_path(@user) %></li>
        </ul>  
      <% end %>
    </div>
  </div> 
  
</section>

<section class="section-owner">
  <%= render 'owner_info', user: @user %>
</section>
 